# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Vb7yvNSs_YEwGQuPTxQ-MIETmhLJlce
"""

import streamlit as st
import torch
import torch.nn.functional as F
from torchvision.utils import make_grid
from model import CVAE
import matplotlib.pyplot as plt
import numpy as np

# Load model
model = CVAE()
model.load_state_dict(torch.load("cvae_mnist.pth", map_location="cpu"))
model.eval()

st.title("✍️ Handwritten Digit Generator")
digit = st.slider("Choose a digit (0-9)", 0, 9, 0)

if st.button("Generate 5 Images"):
    with torch.no_grad():
        labels = torch.tensor([digit] * 5)
        y_onehot = F.one_hot(labels, 10).float()
        z = torch.randn(5, model.latent_dim)
        images = model.decode(z, y_onehot).view(-1, 1, 28, 28)

        grid = make_grid(images, nrow=5, padding=2)
        np_grid = grid.permute(1, 2, 0).numpy()

        st.image(np_grid, caption=f"Generated samples of digit {digit}", width=500)